---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backend.tutorial.kubebuilder.io
  resources:
  - bizservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backend.tutorial.kubebuilder.io
  resources:
  - bizservers/finalizers
  verbs:
  - update
- apiGroups:
  - backend.tutorial.kubebuilder.io
  resources:
  - bizservers/status
  verbs:
  - get
  - patch
  - update
