apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: op-demo
  name: op-demo-operator-role
rules:
  - apiGroups: 
      - apps
    resources: 
      - deployments
      # - configmaps
      # - pods
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "*"
  - apiGroups: 
      - ""
    resources: 
      - pods
    verbs: 
      - "*"
  - apiGroups:
      - "networking.istio.io"
    resources:
      - virtualservices
      - destinationrules
    verbs:
      - "*"
