apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: target-ns-role-binding
  namespace: op-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: op-demo-operator-role
subjects:
- kind: ServiceAccount
  name: operator-new-controller-manager
  namespace: operator-new-system
