apiVersion: backend.tutorial.kubebuilder.io/v1
kind: BizServer
metadata:
  labels:
    app.kubernetes.io/name: bizserver
    app.kubernetes.io/instance: bizserver-sample
    app.kubernetes.io/part-of: operator-new
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-new
  name: bizserver-sample
  namespace: operator-new-system
spec:
  # TODO(user): Add fields here
  server_name: test-demo-server
  image: wnz27/test_server_demo:v1.0.0
  mysql_secret: mysql-test
  public_config: domains-public-config
  virtual_service_name: test-demo-vs
  namespace: op-demo
  service_name: test-demo-service


